# Setting
gpus: [0,1]
seed: 1
debug: False
pretrained_path: None
work_dir: ./workdir
no_progress_bar: False


# Data Loader
# ntu-xsub, ntu-xview, ntu-xsub120, ntu-xset120
dataset: ntu-xsub
dataset_args:
  ntu:
    train_batch_size: 16
    eval_batch_size: 16
    num_frame: 288
    inputs: VB
    transform: False
    root_folder: ./data
    ntu60_path: ../ntu_rgb_d_skeletons
    ntu120_path: ../nturgbd_skeletons_s018_to_s032

# Model
model_type: EHC-GCN
model_args:
  stem_channel: 64
  channel_args: [48,64,128]
  act_type: swish
  att_type: ca
  layer_type: SG
  drop_prob: 0.25
  kernel_size: [5,2]
  expand_ratio: 0
  reduct_ratio: 2
  bias: True
  edge: True

# Optimizer
# SGD, Adam
optimizer: SGD
optimizer_args:
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
  Adam:
    lr: 0.1
    betas: [0.9,0.99]
    weight_decay: 0.0001

# Scheduler
# step, cosine
lr_scheduler: cosine
scheduler_args:
  step:
    max_epoch: 70
    warm_up: 10
    step_lr: [20,50]
  cosine:
    max_epoch: 70
    warm_up: 10
